Repository rancher-sandbox/rancher-desktop, pull requests merged in 2021-12, with the labels that each got.

#1046 [913] Playwright set up - Spectron replacement
  .github/workflows/e2e-test.yaml
  .gitignore
  e2e/config/playw-config.ts
  e2e/main.e2e.spec.ts
  e2e/utils/TestUtils.ts
  package-lock.json
  package.json
  scripts/e2e.mjs
Labels: qa-automation

#1086 WSL: Fix logging with spaces in path.
  src/assets/scripts/service-k3s.initd
  src/assets/scripts/service-wsl-dockerd.initd
  src/k8s-engine/wsl.ts
Labels: platform/windows

#1097 Bump lima-and-qemu
  scripts/download/lima.mjs
Labels: enhancement, lima

#1107 Don't delete the specific routes for the rd0 vmnet interface
  src/assets/lima-config.yaml
Labels: bug, platform/macos

#1067 [936] Cirrus CI - E2E/Integration Pipeline
  .cirrus.yml
Labels: qa-automation

#1136 Lima: Darwin: Don't always use en0 for bridged network.
  src/assets/networks-config.yaml
  src/k8s-engine/lima.ts
Labels: platform/macos, lima
