Repository rancher-sandbox/rancher-desktop, pull requests merged in 2021-11, with the labels that each got.

#926 Allow k3s customization via K3S_EXEC variable
  src/assets/scripts/service-k3s
Labels: enhancement, lima

#906 Attempt to kill any stray qemu process
  src/k8s-engine/lima.ts
Labels: platform/macos, platform/linux

#874 Add Linux packaging files
  .github/workflows/package.yaml
  .gitignore
  README.md
  electron-builder.yml
  flatpak/io.rancherdesktop.app.desktop
  packaging/linux/appimage.yml
  packaging/linux/flatpak.yaml
  packaging/linux/rancher-desktop.appdata.xml
  packaging/linux/rancher-desktop.desktop
  packaging/linux/rancher-desktop.spec
  resources/icons/linux/rancher-desktop.128x128.png
  resources/icons/linux/rancher-desktop.16x16.png
  resources/icons/linux/rancher-desktop.256x256.png
  resources/icons/linux/rancher-desktop.32x32.png
  resources/icons/linux/rancher-desktop.48x48.png
  resources/icons/linux/rancher-desktop.512x512.png
  resources/icons/linux/rancher-desktop.64x64.png
  scripts/build.mjs
  src/k8s-engine/lima.ts
Labels: platform/linux

#945 [GitHub Templates] Bug/Feature issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: documentation

#973 [Improvements] GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation

#958 WSL: Use OpenRC.
  scripts/download/wsl.mjs
  src/assets/scripts/service-k3s
  src/assets/scripts/wsl-launch-k3s
  src/k8s-engine/lima.ts
  src/k8s-engine/wsl.ts
Labels: platform/windows

#933 Support running on M1 (via Rosetta) with native lima and qemu
  .github/workflows/package.yaml
  background.ts
  scripts/download/lima.mjs
  scripts/download/tools.mjs
  src/assets/scripts/install-k3s
  src/k8s-engine/__tests__/k3sHelper.spec.ts
  src/k8s-engine/k3sHelper.ts
  src/k8s-engine/k8s.ts
  src/k8s-engine/lima.ts
  src/k8s-engine/wsl.ts
Labels: enhancement, platform/macos

#914 Release checklist
  docs/development/release-checklist.md
Labels: documentation

#949 [Improvement] ipcRenderer.SendSync to ipcRenderer.on/send
  background.ts
  src/pages/FirstRun.vue
  src/pages/General.vue
  src/pages/Images.vue
  src/pages/K8s.vue
  src/pages/PortForwarding.vue
  src/typings/electron-ipc.d.ts
Labels: enhancement, qa-automation

#1028 K3s: Don't specify group for log file.
  src/assets/scripts/service-k3s.initd
Labels: bug, platform/windows

#1036 Removing the gate on windows first run runtime
  src/pages/FirstRun.vue
Labels: platform/windows
