Repository rancher-sandbox/rancher-desktop, pull requests merged in 2021-05, with the labels that each got.

#242 Initial documentation addition
  docs/README.md
  docs/images.md
  docs/images/windows-notice-1.png
  docs/images/windows-notice-2.png
  docs/installing.md
Labels: documentation

#260 Automatically install WSL in the Windows Installer
  build/add-to-path.ps1
  build/install-wsl.ps1
  build/installer.nsh
  electron-builder.yml
  scripts/build.mjs
Labels: windows

#296 NSIS: Add extra nested `resources` to PATH
  build/add-to-path.ps1
Labels: bug, windows

#292 Provide a `safeRename` function
  package-lock.json
  package.json
  src/k8s-engine/k3sHelper.ts
  src/utils/__tests__/assets/safeRename/safeRename.tar
  src/utils/__tests__/safeRename.spec.ts
  src/utils/safeRename.ts
Labels: bug, windows

#304 Be more careful when processing the config file:
  src/k8s-engine/k3sHelper.ts
  src/k8s-engine/wsl.ts
  src/menu/tray.js
Labels: bug, windows
