Repository rancher-sandbox/rancher-desktop, pull requests merged in 2022-12, with the labels that each got.

#3483 Help buttons, fix colors
  pkg/rancher-desktop/assets/styles/themes/_dark.scss
  pkg/rancher-desktop/assets/styles/themes/_light.scss
  pkg/rancher-desktop/components/Help.vue
Labels: component/ui

#3527 Don't start OpenResty explicitly
  pkg/rancher-desktop/backend/wsl.ts
Labels: kind/quality

#3546 fix image allow list alert reactivity
  pkg/rancher-desktop/pages/images/add.vue
Labels: area/images

#3596 Image Allow list, fix text wrap
  pkg/rancher-desktop/components/Preferences/ContainerEngineAllowedImages.vue
Labels: component/ui, area/preferences

#3616 Update bats scripts for compatibility with upcoming 1.7 release
  bats/tests/helpers/commands.bash
  bats/tests/helpers/containers.bash
  bats/tests/helpers/defaults.bash
  bats/tests/helpers/lima.bash
  bats/tests/helpers/vm.bash
  bats/tests/k8s/wordpress.bats
  bats/tests/registry/creds.bats
Labels: kind/quality, component/ci

#3575 GitHub Actions: Stop using deprecated in-line workflow commands.
  .github/workflows/package.yaml
Labels: kind/quality, component/ci

#3664 Add image, replace plus button with secondary button
  pkg/rancher-desktop/assets/translations/en-us.yaml
  pkg/rancher-desktop/components/ImagesButtonAdd.vue
Labels: component/ui, area/images
