Repository rancher-sandbox/rancher-desktop, pull requests merged in 2022-01, with the labels that each got.

#1164 Separate title section and body
  src/layouts/default.vue
  src/pages/Images.vue
Labels: ui

#1146 [E2E] kubectl deployment test
  .cirrus.yml
  e2e/assets/k8s-deploy-sample/nginx-sample-app.yaml
  e2e/config/playwright-config.ts
  e2e/kubectl.e2e.spec.ts
  e2e/main.e2e.spec.ts
  e2e/utils/TestUtils.ts
  scripts/e2e.mjs
  src/utils/childProcess.ts
  src/utils/logging.ts
Labels: area/qa-automation

#1187 Fix issue templates auto label
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: kind/documentation

#1289 Bump Playwright from 1.17.0 to 1.18.0
  package-lock.json
  package.json
Labels: component/qa-automation

#1202 [E2E] helm deployment test
  .cirrus.yml
  e2e/helm.e2e.spec.ts
  e2e/kubectl.e2e.spec.ts
  e2e/main.e2e.spec.ts
  e2e/utils/TestUtils.ts
Labels: component/qa-automation

#1301 Roll back aliases and bump @playwright/test from 1.17.0 to 1.18.0
  package-lock.json
  package.json
  src/utils/childProcess.ts
  src/utils/logging.ts
Labels: component/qa-automation

#1391 Bump Playwright from 1.18.0 to 1.18.1
  package-lock.json
  package.json
Labels: component/qa-automation

#1402 Project status is no longer "beta"
  src/pages/General.vue
Labels: triage/patch-candidate
