Repository rancher-sandbox/rancher-desktop, pull requests merged in 2022-09, with the labels that each got.

#2894 Update Alpine Lima ISO to 0.2.21
  src/assets/dependencies.yaml
Labels: component/lima

#2940 Don't try to close k3s if k8s is disabled.
  src/backend/lima.ts
Labels: kind/bug

#2964 Diagnostics: kubecontext: Use correct kubectl.
  src/main/diagnostics/kubeContext.ts
Labels: area/diagnostics
