Repository rancher-sandbox/rancher-desktop, pull requests merged in 2022-02, with the labels that each got.

#1423 Bump lima-and-qemu to v1.18
  scripts/download/lima.mjs
Labels: needs-pick

#1449 Rename sudoers file to zzzzz-rancher-desktop-lima
  src/assets/networks-config.yaml
  src/k8s-engine/lima.ts
Labels: needs-pick

#1429 Bump nerdctl to v0.16.1
  scripts/download/lima.mjs
  scripts/download/wsl.mjs
  src/k8s-engine/lima.ts
  src/k8s-engine/wsl.ts
Labels: needs-pick

#1424 Run setup commands inline rather than writing them to a script and running the script.
  src/k8s-engine/lima.ts
Labels: needs-pick

#1302 WSL: Use dnsmasq
  scripts/download/wsl.mjs
  src/assets/scripts/wsl-data.conf
  src/k8s-engine/progressTracker.ts
  src/k8s-engine/wsl.ts
Labels: platform/windows

#1601 Bug template - Improved version placeholders
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: kind/documentation

#1622 Bump playwright and playwright/test from 1.18.1 to 1.19.1
  package-lock.json
  package.json
Labels: component/qa-automation

#1637 WSL: Exclude WSL1 distributions from integration.
  src/k8s-engine/wsl.ts
Labels: kind/enhancement, platform/windows

#1661 WSL: Don't assume where resolv.conf lives.
  src/k8s-engine/wsl.ts
Labels: platform/windows
