Repository rancher-sandbox/rancher-desktop, pull requests merged in 2022-11, with the labels that each got.

#3357 Feature/image allow list
  background.ts
  e2e/pages/preferences/containerEngine.ts
  e2e/preferences.e2e.spec.ts
  e2e/rdctl.e2e.spec.ts
  package-lock.json
  package.json
  pkg/rancher-desktop/assets/specs/command-api.yaml
  pkg/rancher-desktop/assets/translations/en-us.yaml
  pkg/rancher-desktop/components/Alert.vue
  pkg/rancher-desktop/components/Preferences/Alert.vue
  pkg/rancher-desktop/components/Preferences/BodyApplication.vue
  pkg/rancher-desktop/components/Preferences/BodyContainerEngine.vue
  pkg/rancher-desktop/components/Preferences/ContainerEngineAllowedImages.vue
  pkg/rancher-desktop/components/Preferences/ContainerEngineGeneral.vue
  pkg/rancher-desktop/config/transientSettings.ts
  pkg/rancher-desktop/main/commandServer/settingsValidator.ts
  pkg/rancher-desktop/pages/Preferences.vue
  pkg/rancher-desktop/pages/images/add.vue
  pkg/rancher-desktop/store/transientSettings.ts
  pkg/rancher-desktop/utils/filters.ts
  pkg/rancher-desktop/window/preferences.ts
Labels: kind/enhancement, component/ui

#3380 Bump @rancher/components from 0.1.0-alpha.7 to 0.1.0-alpha.8
  package-lock.json
  package.json
Labels: component/dependencies

#3410 screenshots
  .gitignore
  e2e/pages/diagnostics-page.ts
  e2e/pages/images-page.ts
  e2e/pages/nav-page.ts
  e2e/pages/preferences/application.ts
  package.json
  pkg/rancher-desktop/components/DiagnosticsBody.vue
  pkg/rancher-desktop/components/Images.vue
  pkg/rancher-desktop/components/Preferences/ApplicationBehavior.vue
  screenshots/Screenshots.ts
  screenshots/playwright-config.ts
  screenshots/screenshots.e2e.spec.ts
Labels: area/utilities

#3436 image-allow-list, fix alert when enabled
  pkg/rancher-desktop/pages/images/add.vue
Labels: kind/bug

#3409 help buttons
  package-lock.json
  package.json
  pkg/rancher-desktop/components/Help.vue
  pkg/rancher-desktop/components/Preferences/BodyApplication.vue
  pkg/rancher-desktop/components/Preferences/BodyContainerEngine.vue
  pkg/rancher-desktop/components/Preferences/ModalActions.vue
  pkg/rancher-desktop/components/Preferences/ModalBody.vue
  pkg/rancher-desktop/components/Preferences/ModalFooter.vue
  pkg/rancher-desktop/components/Preferences/ModalNav.vue
  pkg/rancher-desktop/config/help.ts
  pkg/rancher-desktop/pages/Preferences.vue
  pkg/rancher-desktop/store/help.ts
  pkg/rancher-desktop/typings/store.d.ts
Labels: component/ui, area/preferences

#3458 Image Allow list, fix typo
  pkg/rancher-desktop/assets/translations/en-us.yaml
Labels: component/ui

#3459 KubernetesError, show-logs feature
  background.ts
  pkg/rancher-desktop/pages/KubernetesError.vue
  pkg/rancher-desktop/pages/Troubleshooting.vue
  pkg/rancher-desktop/typings/electron-ipc.d.ts
Labels: kind/quality

#3449 Preferences, enable Apply button while typing new pattern in Allow List box
  package-lock.json
  package.json
  pkg/rancher-desktop/components/Preferences/ContainerEngineAllowedImages.vue
  pkg/rancher-desktop/store/preferences.ts
Labels: kind/enhancement, component/ui, area/preferences

#3433 screenshots, mock data
  background.ts
  e2e/pages/diagnostics-page.ts
  pkg/rancher-desktop/components/DiagnosticsBody.vue
  pkg/rancher-desktop/main/diagnostics/diagnostics.ts
  pkg/rancher-desktop/main/diagnostics/mockForScreenshots.ts
  pkg/rancher-desktop/main/diagnostics/testCheckers.ts
  screenshots/Screenshots.ts
  screenshots/playwright-config.ts
  screenshots/screenshots.e2e.spec.ts
Labels: kind/enhancement, area/utilities

#3432 Reinstate the 'Run Rancher Desktop' checkbox at end of installation.
  build/wix/dialogs.wxs
Labels: platform/windows, area/installer

#3484 Help button, assign urls
  pkg/rancher-desktop/components/Preferences/BodyApplication.vue
  pkg/rancher-desktop/components/Preferences/BodyContainerEngine.vue
  pkg/rancher-desktop/config/help.ts
Labels: area/config

#3485 Bump @rancher/components
  package-lock.json
  package.json
Labels: component/ui, area/preferences
