Repository rancher-sandbox/rancher-desktop, pull requests merged in 2023-02, with the labels that each got.

#3869 Support moby engine and RD_USE_WINDOWS_EXE in BATS on Windows
  bats/tests/containers/platform.bats
  bats/tests/helpers/commands.bash
  bats/tests/helpers/load.bash
  bats/tests/helpers/utils.bash
  bats/tests/helpers/vm.bash
Labels: kind/quality

#3826 Start-in-background behavior
  background.ts
  pkg/rancher-desktop/layouts/default.vue
  pkg/rancher-desktop/typings/electron-ipc.d.ts
  pkg/rancher-desktop/window/index.ts
Labels: area/preferences

#3917 Remove isWin from screenshots task
  screenshots/screenshots.e2e.spec.ts
Labels: component/e2e, area/utilities

#3935 Bats fixes
  bats/tests/helpers/vm.bash
Labels: kind/quality

#3509 Script collection of screenshots for UI
  pkg/rancher-desktop/window/index.ts
  pkg/rancher-desktop/window/preferences.ts
  screenshots/Screenshots.ts
  screenshots/playwright-config.ts
  screenshots/screenshots.e2e.spec.ts
Labels: area/utilities

#3905 Get creds.bats working on Windows
  bats/tests/helpers/commands.bash
  bats/tests/helpers/defaults.bash
  bats/tests/helpers/utils.bash
  bats/tests/helpers/vm.bash
  bats/tests/registry/creds.bats
Labels: kind/quality

#3893 Add keyboard shortcuts for tab navigation
  pkg/rancher-desktop/layouts/default.vue
  pkg/rancher-desktop/pages/Preferences.vue
  pkg/rancher-desktop/typings/electron-ipc.d.ts
  pkg/rancher-desktop/utils/shortcuts.ts
  pkg/rancher-desktop/utils/typeUtils.ts
  pkg/rancher-desktop/window/index.ts
  pkg/rancher-desktop/window/preferences.ts
Labels: component/ui

#4012 Preferences, change QuitOnClose's label
  pkg/rancher-desktop/assets/translations/en-us.yaml
Labels: component/ui, area/preferences

#4028 screenshots, await directory creation
  screenshots/Screenshots.ts
Labels: area/utilities

#4047 Move Behavior settings inside the `application` group
  background.ts
  e2e/quit-on-close.e2e.spec.ts
  pkg/rancher-desktop/assets/specs/command-api.yaml
  pkg/rancher-desktop/components/Preferences/ApplicationBehavior.vue
  pkg/rancher-desktop/config/__tests__/settings.spec.ts
  pkg/rancher-desktop/config/settings.ts
  pkg/rancher-desktop/main/commandServer/settingsValidator.ts
  pkg/rancher-desktop/window/index.ts
Labels: area/preferences

#4051 screenshots, Readme
  screenshots/README.md
Labels: area/utilities
