Repository rancher-sandbox/rancher-desktop, pull requests merged in 2023-04, with the labels that each got.

#4348 window: Fix extensions dev tool hotkey
  pkg/rancher-desktop/window/index.ts
Labels: kind/bug, area/rdx

#4313 RDX: Host APIs
  bats/tests/extensions/testdata/bin/dummy.cmd
  bats/tests/extensions/testdata/everything.json
  e2e/extensions.e2e.spec.ts
  e2e/rdctl-extensions.e2e.spec.ts
  e2e/utils/TestUtils.ts
  pkg/rancher-desktop/main/extensions/manager.ts
  pkg/rancher-desktop/main/extensions/types.ts
  pkg/rancher-desktop/preload/extensions.ts
  pkg/rancher-desktop/typings/electron-ipc.d.ts
  pkg/rancher-desktop/utils/childProcess.ts
Labels: area/rdx

#4347 RDX: Use compose for images
  bats/tests/extensions/containers.bats
  bats/tests/extensions/install.bats
  pkg/rancher-desktop/main/extensions/extensions.ts
Labels: area/rdx

#4324 RDX: Implement container engine APIs
  e2e/extensions.e2e.spec.ts
  pkg/rancher-desktop/backend/containerClient/nerdctlClient.ts
  pkg/rancher-desktop/backend/containerClient/types.ts
  pkg/rancher-desktop/main/extensions/manager.ts
  pkg/rancher-desktop/preload/extensions.ts
Labels: area/rdx

#4321 RDX: Set up the API synchronously.
  pkg/rancher-desktop/main/extensions/manager.ts
  pkg/rancher-desktop/preload/extensions.ts
  pkg/rancher-desktop/preload/index.ts
  pkg/rancher-desktop/typings/electron-ipc.d.ts
  pkg/rancher-desktop/window/index.ts
Labels: kind/bug, area/rdx

#4369 RDX: Implement running commands in containers
  e2e/extensions.e2e.spec.ts
  pkg/rancher-desktop/backend/containerClient/mobyClient.ts
  pkg/rancher-desktop/backend/containerClient/nerdctlClient.ts
  pkg/rancher-desktop/backend/containerClient/types.ts
  pkg/rancher-desktop/main/extensions/extensions.ts
  pkg/rancher-desktop/main/extensions/manager.ts
Labels: area/rdx

#4392 RDX: Fix missing import
  pkg/rancher-desktop/main/extensions/manager.ts
Labels: kind/bug, area/rdx

#4414 RDX: Don't send events to dead frames
  pkg/rancher-desktop/main/extensions/manager.ts
Labels: kind/bug, area/rdx

#4430 BATS: Fix starting on Windows
  bats/tests/helpers/vm.bash
Labels: kind/bug, platform/windows

#4429 wsl-exec: ensure we use the pid of /sbin/init
  pkg/rancher-desktop/assets/scripts/wsl-exec
Labels: kind/bug, platform/windows

#4459 Toggle icon theme
  pkg/rancher-desktop/components/Nav.vue
Labels: area/rdx

#4481 WSL: Wait for moby socket proxy to stabilize
  pkg/rancher-desktop/backend/wsl.ts
Labels: kind/bug, platform/windows, runtime/moby

#4480 Add logs-explorer screenshot
  pkg/rancher-desktop/utils/_demo_metadata.js
  screenshots/extensions/logs-explorer-0.2.2.png
Labels: component/ui, area/rdx

#4462 RDX: Don't add volumes that already exist
  pkg/rancher-desktop/main/extensions/extensions.ts
Labels: area/rdx

#4516 BATS: update readme
  bats/README.md
Labels: kind/quality, component/bats

#4521 rdctl: win32: fix factory-reset when no data exists.
  src/go/rdctl/pkg/factoryreset/factory_reset_windows.go
Labels: kind/bug, platform/windows, area/rdctl

#4532 Layout: filter out extensions without UI
  pkg/rancher-desktop/layouts/default.vue
Labels: kind/bug, component/ui, area/rdx

#4533 BATS: various extension fixes
  bats/tests/extensions/containers.bats
  bats/tests/extensions/install.bats
  bats/tests/extensions/testdata/Makefile
  bats/tests/extensions/testdata/bin/server.py
  bats/tests/helpers/kubernetes.bash
  bats/tests/k8s/traefik.bats
  bats/tests/k8s/verify-cached-images.bats
  pkg/rancher-desktop/main/extensions/extensions.ts
Labels: kind/bug, area/rdx
