Repository rancher-sandbox/rancher-desktop, pull requests merged in 2023-03, with the labels that each got.

#4072 Don't mount cache and logs directories
  pkg/rancher-desktop/backend/lima.ts
Labels: kind/quality

#4083 Add E2E tests for `startInBackground` setting
  e2e/quit-on-close.e2e.spec.ts
  e2e/start-in-background.e2e.spec.ts
  e2e/utils/TestUtils.ts
Labels: component/e2e, kind/quality

#4199 RDX: Implement protocol handler
  background.ts
  e2e/extensions-protocol.e2e.spec.ts
  e2e/lockedFields.e2e.spec.ts
  e2e/quit-on-close.e2e.spec.ts
  e2e/start-in-background.e2e.spec.ts
  e2e/utils/TestUtils.ts
  pkg/rancher-desktop/backend/lima.ts
  pkg/rancher-desktop/utils/protocols.ts
  pkg/rancher-desktop/window/index.ts
Labels: area/rdx

#4222 Perserve SSH_AUTH_SOCK env variable for nerdctl
  resources/darwin/bin/nerdctl
  resources/linux/bin/nerdctl
Labels: kind/enhancement

#4291 RDX: When getting installed extensions, don't fail if there are none
  pkg/rancher-desktop/main/extensions/manager.ts
Labels: area/rdx
