Repository rancher-sandbox/rancher-desktop, pull requests merged in 2023-11, with the labels that each got.

#5908 Improve errors returned from `rdctl`'s `wsl` package
  src/go/rdctl/pkg/wsl/wsl_windows.go
Labels: kind/quality, component/rdctl

#5992 Adds tooltip for new scenarios & for container name when the `sha` is truncated.
  pkg/rancher-desktop/pages/Containers.vue
Labels: kind/bug

#5875 WiX: Use custom action for installing WSL
  .github/actions/spelling/expect.txt
  README.md
  build/wix-install-wsl.ps1
  build/wix/main.wxs
  build/wix/scope.wxs
  build/wix/verify.wxs
  build/wix/welcome.wxs
  scripts/lib/installer-win32-gen.tsx
  scripts/lib/installer-win32.tsx
  scripts/package.ts
  scripts/windows-setup.ps1
  src/go/wsl-helper/cmd/wsl_info.go
  src/go/wsl-helper/pkg/wsl-utils/dism_windows.go
  src/go/wsl-helper/pkg/wsl-utils/install_windows.go
  src/go/wsl-helper/pkg/wsl-utils/run_windows.go
  src/go/wsl-helper/pkg/wsl-utils/utf16writer_windows.go
  src/go/wsl-helper/pkg/wsl-utils/version_windows.go
  src/go/wsl-helper/pkg/wsl-utils/version_windows_test.go
  src/go/wsl-helper/wix/check_windows.go
  src/go/wsl-helper/wix/doc.go
  src/go/wsl-helper/wix/helpers_windows.go
  src/go/wsl-helper/wix/imports_windows.go
  src/go/wsl-helper/wix/install_windows.go
  src/go/wsl-helper/wix/main_windows.go
Labels: release-note
